backend:
  name: github
  repo: jonasha/jonasha.github.io

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "site/content/about.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
      - label: "Locations Page"
        name: "locations"
        file: "site/content/locations.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Locations
            name: locations
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Address, name: address, widget: string }
